server:
  port: 80
spring:
  application:
    name: cloud-consul-order

  cloud:
    consul:
      host: 42.193.176.54
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true
