server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 42.193.176.54:8849
management:
  endpoints:
    web:
      exposure:
        include: '*'