server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 42.193.176.54:8849
    sentinel:
      transport:
        dashboard: 192.168.200.129:8080
        # 默认端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719


#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
server-url:
  nacos-user-service: http://nacos-payment-provider

# 激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true